### ISSUE TITLE
Wait how do I open the application

### ISSUE THREAD

**Issue by CamuiChan** [Cuyler36/ACSE#1]
I dont know how to open the application or I'm ignorant

**Comment by SMarioMan** [comment]
Currently, @Cuyler36 doesn't have any releases in the repo, since there is work being done to unify the save editors, but you can find and download old releases here: https://github.com/Cuyler36/ACSE-OLD/releases

**Comment by Cuyler36** [comment]
I'm about to release the first version of this editor. I still need to implement the House Editor and finish getting all the Acre Images for the original Animal Crossing.
