### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by xmilliemaex** [Cuyler36/ACSE#12]
every time i open acse and go file>open to pull up my garden_plus.dat file it crashes

**Comment by Cuyler36** [comment]
Can you upload the debug log? It should be in the same directory as the program. Also can you upload your garden_plus.dat file? I'd like to take a look at it.

**Comment by xmilliemaex** [comment]
![screen shot 2017-12-16 at 23 17 14](https://user-images.githubusercontent.com/34218800/34075213-7ea2a3c6-e2b7-11e7-9e4d-e72d592f77d3.png)

There's the debug log. It adds a new line each time it crashes. Won't let me upload my garden_plus.dat file. Definitely isn't corrupt or anything though - works on the online editor and on my console. It doesn't even get to the point of me choosing a file, crashes as soon as I click open. I can screen record it happening if you want.

**Comment by Cuyler36** [comment]
I see you're on MacOS which may be the problem. Although Windows .NET is supported on MacOS, I haven't tested that it works because I don't own a Mac. I'll get an emulator and see if I can't find out why it's crashing before the next release. If you try it on Windows, it should work though!

**Comment by xmilliemaex** [comment]
I use the WINE emulator if that helps. Because it's a .exe and crashes when I click open I think it might be having problems accessing Finder (Mac file explorer), rather than having problems actually running on MacOS.

**Comment by xmilliemaex** [comment]
(I'm a programmer and have had to get Linux programs to run on my Mac)

**Comment by Cuyler36** [comment]
I plan to release a Mac build for it when it's a little more stable. Until then, I can attempt to debug it, but the best thing to try would be a virtual machine running Windows.

**Comment by Cuyler36** [comment]
Closing this since no followup was made.
