### ISSUE TITLE
Potential Errand Bug?

### ISSUE THREAD

**Issue by ProtonicNova** [Cuyler36/ACSE#13]
(Applies to NTSC Animal Crossing for Gamecube)

After editing a save where I had an errand for a villager in progress (going to pick up an item), a strange bug happened. When I select the "I'm picking up!" prompt, the game acts as though I'm delivering the first item in my inventory to the villager.

![image](https://user-images.githubusercontent.com/34487406/33901351-8842f190-df3f-11e7-8c7e-9f9fd73e2ea7.png)
![image](https://user-images.githubusercontent.com/34487406/33901357-8e15bf30-df3f-11e7-84e8-b58dcd1bed8e.png)

If I choose to give it, my player gives nothing, the villager gets angry, and the game softlocks with my player frozen in place mid-giving animation.

![image](https://user-images.githubusercontent.com/34487406/33901370-996d01ea-df3f-11e7-9377-cd5f18fbdf2b.png)
![image](https://user-images.githubusercontent.com/34487406/33901375-9cdbac96-df3f-11e7-9a4a-1cf4a089123f.png)

If I don't choose to give it, the villager just gets angry and I can move, but I still can't complete the errand.

I've been playing this game for years, and I've never encountered this bug on any save file until now, so I think ACSE caused it somehow. I'm using the latest release. What might have caused this, and is there any way to debug this on my end?

**Comment by Cuyler36** [comment]
Did you change your characters name? Or your towns name? What about the villager in question? I haven't experienced this bug myself, so I'll need more information to track down what's happening.

**Comment by ProtonicNova** [comment]
I didn't change any of those names in between saving and loading the game.

I attempted to use a RAM tracker to see what was going on here compared to any other errand. I found a set of addresses that, when talking to a villager involved, store the strings of the villagers' names and the item in question. But changing them doesn't fix the problem and I can't find what processes wrote to those addresses.

I've given up and started a new town, but I kept a copy of this save. I'll let you know if I encounter this bug again, but in the meantime, I can send that GCI file to you if you want to take a look yourself.

**Comment by Cuyler36** [comment]
Sure, that would be useful. Normally when something with villagers happens, it's because either the town or player name changed. In this case, it seems like the game was keeping track of some errand that never existed. I haven't looked at how errands are stored in the save file, but I'll give it a look with your save file and see if I can't get to the bottom of the issue.

**Comment by Cuyler36** [comment]
Closing this due to no followup. The issue will be fixed eventually. It will require removal of the ability to set the player's town name separately from the actual town name.

**Comment by Cuyler36** [comment]
This should be fixed in the newest release. Once I implement the VillagerRelation class, any chance of this happening will be gone.
