### ISSUE TITLE
Save File Load Error with Dolphin Emulator (Australian version compatibility ?)

### ISSUE THREAD

**Issue by AncientMew** [Cuyler36/ACSE#16]
Latest version of ACSE downloaded.
Using Dolphin Emulator to play Animal Crossing for the GameCube.
Exporting the save file to GCI as the tutorial states to do.
ACSE gives an error stating:
"The file [FileName.gci] could not be identified as a valid Animal Crossing save file.
Please ensure you have a valid save file."

Both other export types (.sav and .gcs) have been tried and the same error occurs.
Not sure what to do.

EDIT: After looking at the Closed Issues, I saw that there was previously issues with PAL files (GAFP)
I am using the Australian version which is GAFU, I'm assuming that GAFU is not yet supported and is most likely the issue here.
![savefileerror](https://user-images.githubusercontent.com/36142732/35786416-fd69fbb2-0a1e-11e8-9c8f-86eb9e463e58.png)

**Comment by Cuyler36** [comment]
Can you send me a copy of a save file from the Australian version? I need to check it for compatibility. If it has the same structure (like the PAL version) I can add it in immediately.

Edit:
I was able to find a copy of the Australian Animal Crossing, and verified that the save file is (I believe) exactly the same as the US/PAL version. I've pushed a commit that lets it be loaded now. Support will be in the next release (coming in 3-7 days)! If you want to test it sooner, you'll have to download the source files and build your own copy.

I'm leaving this open until the next release to make sure it's working properly.

**Comment by Cuyler36** [comment]
Closing now because 0.3.0 fixes this.
