### ISSUE TITLE
Villager House Placement

### ISSUE THREAD

**Issue by kevinolmats** [Cuyler36/ACSE#17]
Moving villager houses causes the game to crash on load.

**Comment by Cuyler36** [comment]
In which game? I haven't experienced this for myself, so I would appreciate it if you could upload the associated save file.

**Comment by Cuyler36** [comment]
@Theohhno Does this still happen?

**Comment by Cuyler36** [comment]
Closing this due to no reply. If you have any info, make a new issue @Theohhno
