### ISSUE TITLE
Support for 动物森林 (iQue Animal Forest)

### ISSUE THREAD

**Issue by Jhynjhiruu** [Cuyler36/ACSE#21]
The iQue Player release of Animal Forest has probably the most easily accessible save files of any version not running in an emulator. The Player's .sta save files open fine in this editor, but the fonts are obviously incorrect. Would it be at all possible for support for this game to be added? It could be a great help, though it would probably require a lot of work to correctly display all the assets.
[Here](https://github.com/Cuyler36/ACSE/files/1885962/default.zip)'s a save file from an iQue Player, in case it helps. I have no idea what the .u01 file is, but it might be a part of the save data so I included it.
(`00201b2c` is 动物森林's content ID in hexadecimal, which is how it's used internally by the Player.)

**Comment by Cuyler36** [comment]
I'll look into adding support for it. Unfortunately there is no emulator for the iQue Player and I don't own one, so if it is added, progress may be slow. If you'd like to continue helping me with adding support, then I'd encourage you to join this discord: https://discord.gg/HcpymVA

**Comment by Jhynjhiruu** [comment]
Awesome. There are a whole bunch of people willing to help in some capacity and a lot of us have iQue Players - only a couple have 动物森林 though.
