### ISSUE TITLE
Feature Request - Edit Museum Donations

### ISSUE THREAD

**Issue by SuperMarino** [Cuyler36/ACSE#22]
Any way to change the person associated with a museum donation?

If you use the editor and change a player character's name it changes all donations on the board to say the new name. In game, if you demolish a house (delete the player), the donation board now says "Anonymous" for the donations from that player. So I imagine it must link back to the Player ID per donation, and should be something we could point towards a different player character.

I would also imagine from here you could use this to add/delete donations, giving the ability to clear the museum and start donating again.

**Comment by Cuyler36** [comment]
I've added a "Fill Museum" toolstrip item that fills the museum using the selected player as the donor. It will be in the next update, but if you'd like to get it to work sooner, then you can build your own version and try it out.

**Comment by Cuyler36** [comment]
I'm closing this now, @SuperMarino. Hopefully I answered your question.
