### ISSUE TITLE
Trouble Launching (How to Open?)

### ISSUE THREAD

**Issue by gamebunnycolor** [Cuyler36/ACSE#23]
I don't know if I'm missing something, but I don't know how to get the save editor to run at all.
I can open the old Gamecube only version, but not this one. I'm sorry if I'm missing something obvious.

**Comment by Cuyler36** [comment]
You probably don't have the latest version of .NET installed. Make sure you have .NET 4.5 installed on your system. You can get it for Windows here: https://www.microsoft.com/en-us/download/confirmation.aspx?id=30653

**Comment by gamebunnycolor** [comment]
Thanks a bunch. I'm sorry to have bothered you with such a basic question.
