### ISSUE TITLE
how do you run this?

### ISSUE THREAD

**Issue by shuhsduihdiushiu** [Cuyler36/ACSE#24]
i've literally no clue how to launch it..?

**Comment by Cuyler36** [comment]
Did you download the latest release from the Releases tab? If so, then you should have ACSE.exe and the Resources folder. You need both in the same folder for the program to run.

If you're on a Mac, you won't be able to use this program. If you're on Windows and it won't run, then you probably don't have the latest .NET update installed. You can download that from Microsoft here: https://www.microsoft.com/en-us/download/confirmation.aspx?id=30653

Hopefully that helps you.
