### ISSUE TITLE
Animal Forest Save

### ISSUE THREAD

**Issue by tootyta** [Cuyler36/ACSE#25]
This isn’t an issue with the program, but since you know how to edit the files of Animal Forest, I wanted to ask: Do you know how to fix a corrupted save? Whenever I load my town in Animal Forest from my main player, it freezes and does not continue. However, when I select the new option and play as a new player, it successfully loads the new player. I think this might have something to do with the save numbers or something, because I rememebr fixing a New Leaf Save by changing the last saveID. I’m not sure though, if you could help, then thanks! Sorry for posting this here.

**Comment by Cuyler36** [comment]
Sounds like the checksum is getting corrupted somehow. If you simply open your save with my save editor, then click File -> Save, it'll recalculate the checksum and fix the checksum error. It honestly sounds like whatever memory card/pak or emulator you're using is broken though.
