### ISSUE TITLE
[GCN] Weather Doesn't Save

### ISSUE THREAD

**Issue by tootyta** [Cuyler36/ACSE#29]
Whenever I load my town with the editor, it always says the current weather is Snow. When I change that to something like Rain, it doesn't even set and the town just looks the same.

**Comment by Cuyler36** [comment]
I've identified the problem, and have created a fix for it. It'll be fixed in the next release!

**Comment by tootyta** [comment]
Just tested the build by downloading the source files! It works pretty good now; however, I tested the Fall Leaves option, the weirdest bug came upon me. https://prnt.sc/jn0d9z Whenever I walk, "Ha-Ha!"'s randomly spawn and begin to just stand there. Eventually, if I attempt to run, the game crashes. All the other options work fine though.

**Comment by Cuyler36** [comment]
Since that weather option isn't seen outside of K.K. Slider's music performance, it never had walk/run animations set for it. It probably looks up garbage data and then runs it. Funny thing is, in DnMe+, they fixed it so it works fine.

To resolve it, I added a warning when changing to it (excluding e+), so users will know the risks.

**Comment by tootyta** [comment]
That’s crazy! It’s odd how they wouldn’t use that effect, especially since it gives the perfect “Fall Vibe.” Anyways, thanks! I just wish there was a fix for Animal Crossing GCN. Would there be any possible way to edit the game to add a walking effect for that?

**Comment by Cuyler36** [comment]
An AR/Gecko code, or mod would work. It's definitely possible. I'd have to reverse engineer the weather effect code and figure out what the difference is between AC and e+. I can see about creating a code to fix it.
