### ISSUE TITLE
Finish Animal Crossing: Population Growing Acre Images

### ISSUE THREAD

**Issue by Cuyler36** [Cuyler36/ACSE#3]
Takes a decent amount of time. If anyone would like the modified Dolphin I used to capture the images, I've attached it. Just enable Free Look/Cam in the settings.

[Dolphin-Modified.zip](https://github.com/Cuyler36/ACSE/files/1134403/Dolphin-Modified.zip)

**Comment by Levi86** [comment]
Why don't you just use the acres that are already in the old version of ACSE?

**Comment by Cuyler36** [comment]
I feel they're not descriptive enough. It's hard to tell exactly where a river or bush is, and you can't see the exact structure of the acre. I might add a "map view" option at a later date, though.

**Comment by Levi86** [comment]
Oh, OK, I get it, if I can take screenshots of some of them, I'll send them to you as soon as I get them.

**Comment by Cuyler36** [comment]
If you're willing to help, you need to zoom out until right before the ground (or river if it has one) gets derendered (becomes black). Then take a screenshot and name it ACREID.png. An example would be 0430.png. Make sure the last digit is either: 0, 4, 8, or C (if not, subtract to get to the lower number/letter). Thanks for any help.

**Comment by j0ssi330** [comment]
I want to help but the modified Dolphin application won't open. A 0xc000007b error. Any ideas on how to fix?
Edit: I added openal32.dll to the folder and it worked. 
What's the trick to getting rid of the game clock in the bottom right?

**Comment by Cuyler36** [comment]
I already have someone working on it. I'm not sure why the modified Dolphin isn't working properly. We should have all the acre images documented in the next couple of days (I'm preparing quite a large update at the moment.) In the meantime, if you'd like to help in other ways, you can join the discord server for AC modifying here: https://discord.gg/d9jBFgA

**Comment by Cuyler36** [comment]
This is now completed.
