### ISSUE TITLE
Loads Wild World save as New Leaf save

### ISSUE THREAD

**Issue by Valcuda** [Cuyler36/ACSE#33]
I have an Animal Crossing: Wild World save that I'm trying to edit. But every time I load it, the program loads it as if its a New Leaf save. This leads to it not detecting the things that it expects an Animal Crossing New Leaf save to have, leading to an error.
My save file is using the .sav file extension,  I think this might be the cause of the error, as New Leaf saves also use that file extension.
A simple fix for this would be to let the user decide what the program loads the save as.
I am using the newest build (in fact, I just downloaded it)

**Comment by Cuyler36** [comment]
Can you send me a copy of your save file? I don't see where this would be occurring, as in the save file, the only supported .sav extension is for Wild World.

See here:
https://github.com/Cuyler36/ACSE/blob/6a56ad6fe0784e126a57967c60d51af2c4167ab5/Classes/Save.cs#L121

If you can attach your save file, I'll get to the bottom of it.

Edit:
I'll definitely need a copy of your save file. When I loaded one of my wild world .sav files, it opened properly:
[Screenshot](https://puu.sh/APNMf/1185e82720.png)

**Comment by Valcuda** [comment]
[0389 - Animal Crossing - Wild World (E)(Legacy).zip](https://github.com/Cuyler36/ACSE/files/2156725/0389.-.Animal.Crossing.-.Wild.World.E.Legacy.zip)

**Comment by Valcuda** [comment]
I got the save from my modded DSi, so it could be the modifications fault.

**Comment by Cuyler36** [comment]
The issue turned out to be that instead of the standard 0x40000 byte long save file, the one you dumped was 0x80000. That happens to be the length of one of New Leaf's save files, which is why it detected it as such. I implemented an additional check that fixes the detection in bf19e6b, so it shouldn't happen anymore.

**Comment by Cuyler36** [comment]
Thanks for the report, the next release will contain the fix. In the meantime if you'd like to use it, you can try building ACSE for yourself using Visual Studio 2017 Community edition
