### ISSUE TITLE
[GC] Can't get edited town onto Dolphin memory card

### ISSUE THREAD

**Issue by ghost** [Cuyler36/ACSE#38]
Hi everyone.

Probably just an error on my end but currently trying to get a map I edited in ACSE onto the Dolphin memory card for use in game. After saving my progress in the editor and using the "Import GCI" option to convert my edited file over, the save file displayed shows the name of my unmodded town and loads as my old, unmodded town in game.

The file opens and saves as the new, edited town in ACSE but converts as my old town on Dolphin and ingame, can't seem to stop this from happening.

**Comment by Cuyler36** [comment]
Can you upload a copy of your save file here? If so, I can take a look and see why it's happening.

Edit: It when you imported it to Dolphin, did you first delete the old town? Also verify in Config => GameCube that you're using a Memory Card in Slot A. If you're using a GCI folder instead, place the save file in `C:\Users\YOUR_PC_USERNAME\Documents\Dolphin Emulator\GC\USA\Card A\` instead.

**Comment by Cuyler36** [comment]
If you still can't get it to work, let me know. For the meantime I'm closing this.
