### ISSUE TITLE
.fla gets corrupted upon saving. (Animal Forest)

### ISSUE THREAD

**Issue by LittleCube-hax** [Cuyler36/ACSE#40]
I don't know if I'm doing something wrong, but all I'm doing is opening the .fla of my Animal Forest game in ACSE, saving, and running the emulator, and I get the little K.K. Rider sequence saying that my save got corrupted and I need to reset my town. I have tried this multiple times doing the same thing to the same save and it just keeps corrupting.

**Comment by Cuyler36** [comment]
Are you using the english patch? Also, would you mind sending me a copy of the save file here on GitHub, or DM me it on Discord? My discord is Cuyler#0602.

**Comment by LittleCube-hax** [comment]
Oh man, I didn't even think about that. Yeah, I'm using the english patch.

I'll upload the file [here](https://github.com/Cuyler36/ACSE/files/2398330/ANIMAL.FOREST.unknown.rom.fla.zip).

**Comment by Cuyler36** [comment]
Can you try the save file without modifying it after saving the game and then restarting the emulator? I had save issues with the english patch that weren't related to ACSE, but rather a flaw in the patch that corrupts save data. If it works fine, then try saving it through ACSE (with no changes) and see if it will load then.

**Comment by Cuyler36** [comment]
You might have to create a new save file if you don't have an unmodified copy to test.

**Comment by LittleCube-hax** [comment]
No, that didn't work. I loaded it, saved again, closed the emulator, opened the emulator, checked it, it works fine, then I open it in ACSE and save, open the emulator again and I see K.K.

I think it might be important to add that I've time traveled and so I have to change my date and time to get the game to load at all, otherwise the game freezes.

**Comment by Cuyler36** [comment]
I've found the issue. It's related to the iQue Player Animal Forest support and the English Patch messing with save data values. I'll get a fix pushed out soon!

**Comment by LittleCube-hax** [comment]
Fantastic! Glad we've found the problem.

**Comment by Cuyler36** [comment]
This is fixed now. Thanks for the report! If you'd like to try it out, you'll need to build ACSE yourself.
