### ISSUE TITLE
"Empty (buried)" spots on the map not disappearing, even after I make changes to the save file

### ISSUE THREAD

**Issue by 03bgood** [Cuyler36/ACSE#45]
I think I've stumbled across a serious bug. The "Empty (buried)" spots will not disappear, even after saving. I accdently put some of them in the water and they will not go away, even if I replace them with another item, then delete that item. Upon reloading the save, the "Empty (buried)" spots come back

**Comment by 03bgood** [comment]
![capture](https://user-images.githubusercontent.com/32383447/49428541-f17f1900-f76b-11e8-8406-cd78da030efd.PNG)

**Comment by 03bgood** [comment]
Managed to fix it by removing the portion of the river and adding land and putting bells (10,000) in those spots, dug them up. Went back to the editor and added back the river w/ bridge. I seem to have fixed it.

**Comment by 03bgood** [comment]
![capture 2](https://user-images.githubusercontent.com/32383447/49430169-f5149f00-f76f-11e8-8628-fbcc88162393.PNG)

**Comment by Cuyler36** [comment]
@03bgood Thanks for the bug report! Make sure you are either build from the source code or using the development binaries!
