### ISSUE TITLE
Problem with Animal Crossing Wild World shops.

### ISSUE THREAD

**Issue by Vinnievovi** [Cuyler36/ACSE#50]
On Animals Crossing Wild World, when you go from one shop to another, (ex. From nook n' go to nookington) the number of available items in the store does not increase, rest the same number of items you had before changing shop with the tool.

**Comment by Cuyler36** [comment]
This is a known issue. There is an internal spend (sales) sum value that is independent of the shop you place that decides what "size" the shop is stock-wise.
