### ISSUE TITLE
[GameCube] AC:CG switching player tabs in app doesn't update face and birthday correctly

### ISSUE THREAD

**Issue by Gameplayer9198** [Cuyler36/ACSE#53]
Useful info?: Playing game via Nintendont (with an emulated memory card) on Wii exported & imported .gci via latest stable dolphin. On a windows 10 64bit PC

Issue: Switching between player tabs some info (face and birthday) sticks and doesn't update correctly.

**Comment by Cuyler36** [comment]
I cannot replicate this. Are you using the dev release?
