### ISSUE TITLE
Edited saves not compatible with translated Animal Crossing E+

### ISSUE THREAD

**Issue by ghost** [Cuyler36/ACSE#55]
When I export my dolphin save it is in the USA format but after I edit a save it is saved in the JPN format which Dolphin won't allow me to import. Dolphin will allow me to import the edited save into the JPN memory card but not the USA one. 
Maybe this can be fixed if there is an option to save the edited save in either the USA or JPN format.
I am using the latest dev version of ACSE and Dolphin.

**Comment by Cuyler36** [comment]
Something isn't right here. What do you mean by "JPN" format? You should be using GCI Folder save types to avoid using the memcard manager altogether.

**Comment by ghost** [comment]
So I switched over to using GCI Folder and it works perfectly. 
It might help if there is something in the readme about using GCI Folders over Dolphin memory card.
Closing the issue.
