### ISSUE TITLE
[GC] Appears to corrupt island data 

### ISSUE THREAD

**Issue by ghost** [Cuyler36/ACSE#62]
Game Version: Animal Crossing GameCube, North American version (ID GAFE01)
Release: ACSE 0.4.1
Emulator: Dolphin 5.0-11719
OS: Ubuntu 19.10 x86_64
(ACSE run through WINE with .NET 4.7.2 installed. Issue persists on Windows 10)

Issue:
Animal Island cells are removed upon modification of game save, leaving unloaded areas.
![image](https://user-images.githubusercontent.com/43617576/79052355-85cc7c00-7bfb-11ea-856b-3bb198bf31b8.png)

Reproducing:
Upon editing a save, exiting, and reloading a modified save, ACSE properly loads the modified cells. Upon loading of modified save, Animal Crossing deletes the cells. Exporting the reloaded, modified save and opening it in ACSE shows the cells have no acre data.
![image](https://user-images.githubusercontent.com/43617576/79052356-8d8c2080-7bfb-11ea-8d9a-8954f987faeb.png)

The cells do not appear replaceable through further edits.

Additional information:
AR codes applied when discovering this bug (Rolf's 'Go Anywhere' and '16:9 Widescreen 2.0') **do not** appear to affect island generation. This was tested by creating a new town and visiting the island.
![image](https://user-images.githubusercontent.com/43617576/79052357-93820180-7bfb-11ea-9369-bcf5c3b22f0e.png)
Debt does not appear to effect island generation.

**Comment by ghost** [comment]
I have confirmed that other blocks may be placed through ACSE in place of the island (grass, etc.) without the cells being unloaded.
I have also confirmed that island cells may be placed in _other_ cells without being unloaded.
In an interesting test, __all__ ocean cells were replaced with island cells. No cells were unloaded. This was not reproduceable with grass cells. Could this be an undocumented issue with adjacent cells?

**Comment by ghost** [comment]
Closing issue due to increasing difficulty in replication.

**Comment by Daddu3** [comment]
https://github.com/Cuyler36/ACSE/issues/121

This seems pretty closely related to this issue.
