### ISSUE TITLE
(ACCF) Player Find Error

### ISSUE THREAD

**Issue by aoisdanwio** [Cuyler36/ACSE#66]
Hello, when i run the application and open my dolphin save file, a pop up text box shows up and says "No Player was found on the file!" How can I fix this??

**Comment by d3itii** [comment]
By dolphin save file - do you mean a .GCI file containing your Animal Crossing town exported from Dolphin, or the virtual memory card Dolphin typically saves all games on?

**Comment by aoisdanwio** [comment]
the virtual dolphin memory card (the rvforest.dat you find when you right click the banner and open wii save folder)

**Comment by d3itii** [comment]
I'm unable to reproduce this. There may be a debug.log file in the same directory as ACSE. Can you upload it if there is?

**Comment by aoisdanwio** [comment]
I can't find it so i'll just upload the file here

[ACSE.zip](https://github.com/Cuyler36/ACSE/files/4820007/ACSE.zip)

**Comment by Cuyler36** [comment]
Please attach your rvforest.dat file (Documents/Dolphin Emulator/Wii/title/00010000/52555545/data/rvforest.dat)
