### ISSUE TITLE
ACSE 0.4.1 “No Player Found” Wild World

### ISSUE THREAD

**Issue by galaxyjack** [Cuyler36/ACSE#69]
When I try to open my Wild World save file in acse it gives me an error “Player Not Found” but i have a player on that file .

**Comment by Cuyler36** [comment]
Can you attach your save file here?

**Comment by galaxyjack** [comment]
https://drive.google.com/file/d/19lBAtK4OKgTH4EkGLEkiWnT6Jl-JiT54/view?usp=sharing here it is

**Comment by Cuyler36** [comment]
Thanks, I'll look into it shortly! I'll close this issue when I figure out if there's anything wrong and resolve it.

**Comment by Cuyler36** [comment]
Hi, your save file didn't dump or save right. As you can see [here](https://puu.sh/GlP1p/364ac8fbc9.png), all the data is FF. Please try re-dumping your game.

**Comment by galaxyjack** [comment]
How would i do that because that is my save file from my rom on twilightmenu++

**Comment by Cuyler36** [comment]
I'm not sure, but that file is corrupt. You should be able to access the save file from the SD card though.
