### ISSUE TITLE
How to launch program?

### ISSUE THREAD

**Issue by owenwastaken** [Cuyler36/ACSE#71]
I am a bit new to this stuff and I have no clue how to run it. There is no executable file and running it in visual studio just gives some errors.

**Comment by Cuyler36** [comment]
Please download the latest release from the Releases tab. What you downloaded is the source code, and cannot be run without some knowledge.

https://github.com/Cuyler36/ACSE/releases

**Comment by owenwastaken** [comment]
Ohhhhh. Sorry about that!
