### ISSUE TITLE
Am I missing some file?

### ISSUE THREAD

**Issue by orbitalkartoffel** [Cuyler36/ACSE#89]
Hey, I just downloaded this editor but I can't seem to find a .exe to use this editor... I looked for everything but I can't find the correct file to actually start using the editor, I have my save file ready but just missing the file or .exe to start the program! PLS HELP!

**Comment by justablobthatdoestuff** [comment]
If you go to the option the says master and next to it says "1 branch", click tags and then view all tags.
Then you can select any one of those and they have an .exe file in them. I recommend to choose ACSE-Dev.

**Comment by Cuyler36** [comment]
You can download files from the release page https://github.com/Cuyler36/ACSE/releases
