### ISSUE TITLE
Various Suggestion and Willing to Help!

### ISSUE THREAD

**Issue by FormulaN0ne** [Cuyler36/ACSE#9]
Hey @Cuyler36 , recently I found this software and have been really excited using it. I tried looking up tutorials on youtube, but there were none. After about 4 hours of tinkering and such I have gotten a hang of the software and I feel inspired to make a few tutorials with the approval of you. There were a few things with the software that I found to be annoying after a while, most having to do with the acre editor tool. The first is that while it is useful to have the option to see every layer of a certain acre (lowest, lower, middle, upper) it really clutters the screen and makes looking for acres difficult. The next issue might just pertain to my level of understanding, but I feel like the naming system for acres is kind of inconsistent. Also This last one isn't really much of a problem if the others are taken into account, but if there was an option to switch between the acres being organized by AR code (like it is) and by name it could make for a more user friendly interface. If you need help I can certainly do my best with whatever assignment you would like me to do. I don't know C#, but I can learn if you need me to. Thank you so much for this wonderful software and if you would like to hear more please message me.

**Comment by FormulaN0ne** [comment]
One note I would like to make is that I am using the old version and I haven't been able to get the updated version running quite yet.

**Comment by Cuyler36** [comment]
I believe the newest version fixes that. Sorry for the super late reply, I never got notified of your comment. I've been working on translating DnMe+ to English, so I haven't spent too much time on ACSE recently. An update is coming soon though! If you're interested with helping in any way, and you have a discord account, join this discord server: https://discord.gg/d9jBFgA
